import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
import style from "./layout.module.scss";
import PlantProviderWrapper from "./PlantProviderWrapper";
import HortusProviderWrapper from "./HortusProviderWrapper";



const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "900"], 
  variable: "--font-roboto", 
});

export const metadata: Metadata = {
  title: "Hortus.Live",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <PlantProviderWrapper>
          <HortusProviderWrapper>
            <div className={style.container}>
            <NavBar/>
            
              {children}

            </div>
          </HortusProviderWrapper>
        </PlantProviderWrapper>
      </body>
    </html>
  );
}
